### ISSUE TITLE
Missing `multiple` props on FileUpload Component

### ISSUE THREAD

**Issue by blue-rigel** [GovTechSG/sgds-govtech-react#146]
File upload component "@govtechsg/sgds-react/FileUpload" doesn't allow props to modify `multiple` props of the input. 

We need the `multiple` as props to enforce single file selection.

**Comment by clukhei** [comment]
Thanks I propose the following changes to be similar to HTML input element for files.

By default, FileUpload Component multiple prop will be false. If multiple files required, multiple=true 

Single file usage
```<FileUpload /> ``` 

Multiple file usage
```<FileUpload multiple />
