### ISSUE TITLE
Masthead Component

### ISSUE THREAD

**Issue by hermawan-hadi** [GovTechSG/sgds-govtech-react#153]
Hello! 

May I know if the masthead component (https://www.designsystem.tech.gov.sg/components/official-government-banner) will be added to this library? Thanks!

**Comment by clukhei** [comment]
Hello @hermawan-hadi at the moment there is no plans in adding masthead into this library. Please watch out for upcoming web component library for the masthead component. https://github.com/GovTechSG/sgds-web-component
The release candidate version 1 is soon to be released somewhere around  next week.

The masthead component there can be easily used directly in react.

**Comment by clukhei** [comment]
@hermawan-hadi Please checkout our web components library with masthead released https://github.com/GovTechSG/sgds-web-component/releases/tag/v1.0.0-rc.0

I will close this issue then
