### ISSUE TITLE
Tailwind implementation

### ISSUE THREAD

**Issue by victorkardel** [GovTechSG/sgds-govtech-react#208]
### Prerequisites

- [X] I have [searched](https://github.com/GovTechSG/sgds-govtech-react/issues) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/GovTechSG/sgds-govtech-react/blob/v2/CONTRIBUTING.md)

### Proposal

How hard is to implement tailwind ?

### Motivation and context

I wan't to create an similar react-design-component library but with tailwind.

**Comment by clukhei** [comment]
Hey @vcctm , closing this thread as this is an issue related to our library
