### ISSUE TITLE
Adding the option to show the last page in the pagination components

### ISSUE THREAD

**Issue by xyngfei** [GovTechSG/sgds-govtech-react#213]
### Prerequisites

- [X] I have [searched](https://github.com/GovTechSG/sgds-govtech-react/issues) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/GovTechSG/sgds-govtech-react/blob/v2/CONTRIBUTING.md)

### Proposal

Is there any page to improve the pagination components?
https://www.designsystem.tech.gov.sg/components/pagination

If I look the the sample from sgds site, it will display the last page to allow the user to select. However, refer to the storybook, the example does not have the sample to display the last page in the pagination components

https://react.designsystem.tech.gov.sg/?path=/docs/components-pagination--basic

Any idea how if I wish to display last page in the pagination components?

### Motivation and context

To let user have the option to navigate to the last page directly.

**Comment by clukhei** [comment]
@xyngfei the pagination props for first page and last page are exposed in [v2.4.0](https://github.com/GovTechSG/sgds-govtech-react/releases/tag/v2.4.0)

```
<Pagination
... 
showLastPage={true}
/>
```
Storybook controls example: 
https://react.designsystem.tech.gov.sg/?path=/story/components-pagination--basic&args=showLastPage:true
