### ISSUE TITLE
Where is the Masthead Component?

### ISSUE THREAD

**Issue by clukhei** [GovTechSG/sgds-govtech-react#249]
### Prerequisites

- [X] I have [searched](https://github.com/GovTechSG/sgds-govtech-react/issues) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/GovTechSG/sgds-govtech-react/blob/v2/CONTRIBUTING.md)

### Describe the issue

I have looked through storybook documentation and cannot find the Masthead or Official Government Banner from `govtechsg/sgds-react` library. 

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### Describe your frontend stack. What version of React and @govtechsg/sgds-react are you using? CSR or SSR?

React v2.5.2

**Comment by clukhei** [comment]
Masthead component seats in the web component library under SGDS. 

1) Install the web component library 

```npm install @govtechsg/sgds-web-component```

2) Import the React wrapped form of the Masthead web component

``` jsx
import SgdsMasthead from "@govtechsg/sgds-web-component/react/masthead/index.js"

const GovernmentBanner = () => (
  return <SgdsMasthead></SgdsMasthead>
);

export default GovernmentBanner;
```

For more information on the library : https://www.webcomponent.designsystem.tech.gov.sg/?path=/story/getting-started-introduction--page

Masthead Documentation: https://www.webcomponent.designsystem.tech.gov.sg/?path=/docs/components-masthead--basic

**Comment by soedar** [comment]
I think the readme of https://github.com/GovTechSG/sgds-masthead/tree/master should include a link to this post, if this post is not pinned. There probably are quite a few projects still using the old masthead (~540 download this week), and the migration steps is not really straightforward imo.

---

I was running into an issue where importing the `@govtechsg/sgds-web-component` in a Next.js/T3 project (probably due to Server Side Rending). I got the following error: 

```
ReferenceError: HTMLElement is not defined
```

A way to resolve this is to create a client component that wraps the `SgdsMasthead`, which is dynamically imported without ssr:

```typescript
// _components/masthead.tsx
'use client'

import dynamic from 'next/dynamic';

const SgdsMasthead = dynamic(() => import('@govtechsg/sgds-web-component/react/masthead/index.js'), {
  ssr: false,
});

export default SgdsMasthead;
```

```typescript
// layout.tsx
import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import SgdsMasthead from "./_components/masthead"

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <SgdsMasthead />
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
```

**Comment by clukhei** [comment]
pinned! https://github.com/GovTechSG/sgds-masthead/issues

@soedar  yup nextjs usage with web component has another level of complexity because web components cant be server rendered. 

The documentation about nextjs and web components is here. Another way is to load it via Script to make it fully client
https://webcomponent.designsystem.tech.gov.sg/?path=/docs/getting-started-frameworks-nextjs--docs

We have also just released v2 of web components, do check it out! Migration guide here
https://webcomponent.designsystem.tech.gov.sg/?path=/docs/getting-started-migration--docs

**Comment by soedar** [comment]
Awesome! Congrats on the release!
