### ISSUE TITLE
Enhance Combo Box Filtering: Support "includes" Search in Addition to "startsWith"

### ISSUE THREAD

**Issue by elsonlim** [GovTechSG/sgds-govtech-react#255]
### Prerequisites

- [X] I have [searched](https://github.com/GovTechSG/sgds-govtech-react/issues) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/GovTechSG/sgds-govtech-react/blob/v2/CONTRIBUTING.md)

### Proposal

<img width="395" alt="image" src="https://github.com/user-attachments/assets/432930b3-a007-4778-8dd5-039d49f81580">

Propose enhancing the combo box filtering mechanism to include a "includes" search behaviour alongside the existing "starts with" behaviour. This means that when a user types into the combo box, the filtering will identify and display items that have the entered text anywhere within their label, not just at the beginning.

For instance, if a user types "MOF", the filtered results should include items like "Ministry Of Fun (MOF)" even though "MOF" doesn't appear at the start. This would greatly improve the user experience, making it easier to find the desired item, especially in cases where the user has only partial information or remembers a keyword from the middle of the item's label.

### Motivation and context

The current "starts with" filtering behaviour in combo boxes can be limiting, especially when users:

- Do not remember the exact beginning of the item they are looking for
- Have only partial information or a keyword from the middle of the item's label
- Want to quickly filter down a large list of items based on a specific term

By supporting "includes" search, we can:
- Improve the overall user experience and efficiency when interacting with combo boxes
- Make it easier for users to find the desired item, even with incomplete or imprecise information
- Align the combo box filtering behavior with common search patterns and user expectations

**Comment by clukhei** [comment]
@elsonlim  
 please update `@govtechsg/sgds-react` to v2.7.0 .

Implemented `filterMethod` prop with `include` search.  This prop also accepts a custom function if you would like to apply your own [customised filtering](https://dev.react.designsystem.tech.gov.sg/?path=/docs/components-combobox--custom-filter)

```
<Combobox
  filterMethod="includes"
  ...
/>
```

See docs https://dev.react.designsystem.tech.gov.sg/?path=/docs/components-combobox--includes-filter
