### ISSUE TITLE
onClick event of child button is blocked by Tooltip

### ISSUE THREAD

**Issue by min-marn-oo-hive** [GovTechSG/sgds-govtech-react#261]
### Prerequisites

- [X] I have [searched](https://github.com/GovTechSG/sgds-govtech-react/issues) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/GovTechSG/sgds-govtech-react/blob/v2/CONTRIBUTING.md)

### Describe the issue

https://react.designsystem.tech.gov.sg/?path=/docs/components-tooltip--basic

- onClick event of child `Button` is somehow not registered if it is wrapped by the `Tooltip` component
- `Tooltip` component also does not support `onClick` event handler

- Can we get option to hide close button for `click` type `Tooltip`

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### Describe your frontend stack. What version of React and @govtechsg/sgds-react are you using? CSR or SSR?

2.3.4

**Comment by clukhei** [comment]
@min-marn-oo-hive whats the rationale for having to hide close button for click type tooltip and onClick handler on tooltip? The close button was made compulsory for clickable tooltips due to a ux decision that the user must know how to close the tooltip. 

In what case would you need to perform side effect on clicking a tooltip? Tooltip should be purely informational with no action.

**Comment by min-marn-oo-hive** [comment]
@clukhei to clarify further
```
onClick event of child Button is somehow not registered if it is wrapped by the Tooltip component
```
this is the main issue that we have with `Tooltip` component at the moment. Once that is fixed the second point can be ignored. Rationale is, there needs to be a way for us to detect the `onClick` event and trigger side actions. Whether be it the onClick event of the `Tooltip` or the `Button`.



As for `Can we get option to hide close button for click type Tooltip`, the alignment of the close button looks a bit off. That's why I was wondering if SGDS can provide option for us to hide the close button and just have the Tooltip disappear automatically.

<img width="136" alt="Screenshot 2024-09-04 at 11 29 16 AM" src="https://github.com/user-attachments/assets/2c57552a-6040-4965-9bbd-1e09c77d32e7">

**Comment by clukhei** [comment]
@min-marn-oo-hive The tooltip has been updated with the new UI with close button removed in the latest version. As for issue `onClick event of child Button is somehow not registered...`. It seems more like a wrong usage of a clickable tooltip. 

Your designer will reach out to you for the new changes.

**Comment by jankymonkey** [comment]
Hello! I'd like to reopen this issue as we're still experiencing problems with the tooltip in the following scenario:

- The onClick event of a child Button is not firing when it's wrapped inside the Tooltip component.

We followed the example provided in the Storybook, where the Button is a direct child of the Tooltip, but the onClick handler does not seem to trigger as expected.

Here’s a simplified example:

```js
<Tooltip content="Tooltip blocks onClick">
  <Button
    onClick={() => {
      console.log('clicked');
    }}
  >
    Doesn't work
  </Button>
</Tooltip>
```

You can reproduce the issue using this StackBlitz snippet: https://stackblitz.com/edit/react-dti25svn?file=src%2FApp.js

Could you please advise on how we might use the Tooltip with a Button in this type of scenario? Thank you!
