### ISSUE TITLE
Selecting an option in combobox triggers a page reload

### ISSUE THREAD

**Issue by clye-cog** [GovTechSG/sgds-govtech-react#269]
### Prerequisites

- [X] I have [searched](https://github.com/GovTechSG/sgds-govtech-react/issues) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/GovTechSG/sgds-govtech-react/blob/v2/CONTRIBUTING.md)

### Describe the issue

Selecting an option in combobox does not natively come with the e.preventDefault(). This issue also appeared in the DatePicker component when the arrows for the months were clicked, but was resolved in v2.7.2. The e.preventDefault() should come out of the box in the component and we should not need to add this line of code in our app.

https://github.com/user-attachments/assets/51323196-0fb6-4fd7-8384-61865b5ddbeb

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### Describe your frontend stack. What version of React and @govtechsg/sgds-react are you using? CSR or SSR?

NextJS Typescript React

**Comment by clukhei** [comment]
@clye-cog  fix is released in v2.7.3
