### ISSUE TITLE
Combobox menu not being hydrated with new data even though state is already in

### ISSUE THREAD

**Issue by clye-cog** [GovTechSG/sgds-govtech-react#271]
### Prerequisites

- [X] I have [searched](https://github.com/GovTechSG/sgds-govtech-react/issues) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/GovTechSG/sgds-govtech-react/blob/v2/CONTRIBUTING.md)

### Describe the issue

Combobox is not hydrated with data after list is populated with an initial api call.
Probably a useEffect dependency or something?
Reference: https://github.com/user-attachments/assets/520965c7-76bb-4da7-9410-e87e15171267

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### Describe your frontend stack. What version of React and @govtechsg/sgds-react are you using? CSR or SSR?

NextJS Typescript React, sgds-react 2.7.2

**Comment by clukhei** [comment]
@clye-cog fix is released in v2.7.3 

here's the demo https://react.designsystem.tech.gov.sg/?path=/docs/components-combobox--demo-with-data-fetching
and code snippet

**Comment by clye-cog** [comment]
Hi @clukhei , thanks a lot 💯
