### ISSUE TITLE
Button type on the Button and Dropdown component

### ISSUE THREAD

**Issue by hanstf** [GovTechSG/sgds-govtech-react#43]
Our project is using ``Button`` and ``Dropdown`` for our internal navigation without doing a submit. Since we cannot add the button type, the ``Button`` and ``Dropdown`` is keep on submitting the page.
Is it possible to add the ``type`` props ?

**Comment by hanstf** [comment]
This PR, https://github.com/GovTechSG/sgds-govtech-react/pull/42 will fix the ``Button``, but then for the ``Dropdown``, since the button is wrapped inside a div, should I create a new PR specifically for the ``type`` props ?

**Comment by weijunyu** [comment]
Thanks Hans, we'll review #42 as soon as possible. 
For the dropdown component, since the problem actually also stems from the Button component, the changes would likely be simply changing `<button>` to `<Button>` within the component itself.

**Comment by hanstf** [comment]
the version ^0.2.7 solves all of out issues. Thanks!
