### ISSUE TITLE
Render the Button component with an actual <button>

### ISSUE THREAD

**Issue by Neurrone** [GovTechSG/sgds-govtech-react#8]
1. Buttons are rendered using a `<a>` tag, which should only be used for links. I suggest using an actual `<button>` element instead.
	
	* This would cause confusion for screen reader users, since the expectation of a link is that it moves you to a new page of the application, while buttons update something within the same page. They will also be read as links, not buttons. 
	* The disabled attribute will also not be read, since its not recognized on links, but is conveyed for buttons. The conditional if statement that executes the onclick handler will no longer be needed, since the browser prevents users from interacting with a `<button>` with the `disabled` attribute.
	* Links without valid hrefs are not keyboard focusable by default, the disabled jsx lint warns about this.

2. Add `onFocus` and `onBlur` events, which are roughly the keyboard equivalent of `onMouseEnter` and `onMouseLeave` so that keyboard users can also activate this functionality.

**Comment by weijunyu** [comment]
Thanks Dickson! Please let us know if there are any more issues

**Comment by Neurrone** [comment]
Thanks @weijunyu for fixing this so quickly. The [button docs](https://www.designsystem.gov.sg/docs/button/) still reflect the old markup style, is that code in a separate repo?

**Comment by Sylphias** [comment]
Hey Dickson! We have two separate repos. The react repo is built on the main SGDS repo. We do not have separate documentation for React at the moment unfortunately. I'll put up an issue there and we'll resolve it asap!  Future issues with documentation can be filed at https://github.com/GovTechSG/sgds first!
